### ISSUE TITLE
Extract command uses wrong option

### ISSUE THREAD

**Issue by tikeyknax** [btittelbach/openmtbmap_openvelomap_linux#17]
Running the script with the map veloaustralia-oceania.exe, one gets the error message
`ERROR: Could not find 6*.img file after extracting veloaustralia-oceania.exe`
Further inspection shows that the files of the map have been extracted to subdirectories `???`:
`ls -la OMTB_tmp/
total 20
drwxr-xr-x 5 tikey tikey 4096 Jan 21 18:32 ./
drwxr-xr-x 3 tikey tikey 4096 Jan 21 18:33 ../
drwx------ 3 tikey tikey 4096 Jan 21 18:32 ???/
drwx------ 3 tikey tikey 4096 Jan 21 18:32 ???/
drwx------ 3 tikey tikey 4096 Jan 21 18:32 ???/`

This could be fixed by changing the 7z extract command from x to e in line 154.

**Comment by btittelbach** [comment]
Thanks! fixed in commit 8c022145da6165837c3f084397870bc2b1e89382
